//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_4_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skins
    {
        public System.Guid Id { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Category { get; set; }
        public string Rarity { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> SoldCount { get; set; }
    }
}
